---
# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

- name: "Install Node.js 13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: "install docker."
#   become: true
#   apt:
#     name: ["docker.io"]
#     state: latest
#     update_cache: yes

# - name: sudo usermod -aG docker root
#   become: True
#   shell:
#     cmd: "usermod -aG docker ubuntu"
#     chdir: .

# - name: Install docker-compose
#   remote_user: ubuntu
#   get_url:
#     url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: "u+x,g+x,o+x"

# - copy:
#     src: /home/circleci/project/util/docker-compose.yml
#     dest: /home/ubuntu/

# - name: Run PostgresQL DB
#   become: True
#   shell:
#     cmd: "docker-compose -f docker-compose.yml up -d"
#     chdir: .
