# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glee
    ports:
      - "5532:5432"


# # docker-compose.yml
# version: "3"
# services:
#   database:
#     image: "postgres"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=admin123
#       - POSTGRES_DB=postgres
#     ports:
#       - "5432:5432"
